baseURL = "https://sandeep.sh/"
languageCode = "en-us"
title = "sandeep.sh"
DefaultContentLanguage = "en"

theme = "hugo-journal"

[params]
  description = "Notes and thoughts"
  githubUsername = "TunedMystic"
  twitterUsername = "tunedmystic"
  tagline = "Notes and thoughts"

[author]
  name = "Sandeep.sh"
  homepage = "https://sandeep.sh/"
